apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  ports:
  - port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    app: flask
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: flask
      name: flask
    spec:
      containers:
      - image: renjubino/task1jenk:latest
        name: flask
        env:
          - name: YOUR_NAME
            #valueFrom:
            #  secretKeyRef:
            #    name: your-name
            #    key: yourname
            value: {{YOUR_NAME}}
        ports:
        - containerPort: 5500